allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bcrypt: set this to true or false
  core-js-pure: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  unrs-resolver: true
